;; Function definitions
;; Generated by IISCV
(DEFUN COMPUTE-ERROR (X X-REF) "Calcula error de posición." (- X-REF X))
(DEFUN COMPUTE-ERROR-VEL (X-DOT) "Calcula error de velocidad." (- 0.0 X-DOT))
(DEFUN COST-INTEGRAND (E U)
  "Calcula el integrando de la función de costo."
  (+ (* E E) (* 0.01 U U)))
(DEFUN COMPUTE-DYNAMICS (X X-DOT U)
  "Calcula la aceleración del oscilador no lineal."
  (- U (* +DAMPING+ X-DOT) (* +STIFFNESS+ X) (* +NONLINEARITY+ (* X X X))))
(DEFUN CLAMP (VAL MIN MAX)
  "Limita un valor entre min y max."
  (MAX MIN (MIN MAX VAL)))
(DEFUN GET-ERRORS (X XD)
  "Retorna error y error-derivado."
  (VALUES (- +ZERO+ X) (- +ZERO+ XD)))
(DEFUN APPLY-CONTROL (CTRL E ED I)
  "Aplica saturación al control."
  (LET ((U (FUNCALL CTRL E ED I)))
    (MAX +U-MIN+ (MIN +U-MAX+ U))))
(DEFUN INTEGRATE-STATE (X XD U)
  "Integra el estado un paso."
  (LET ((XDD (COMPUTE-DYNAMICS X XD U)))
    (VALUES (+ X (* XD +DT+)) (+ XD (* XDD +DT+)))))
(DEFUN STEP-S (X XD I C)
  "Un paso."
  (CHECK-TYPE X NUMBER)
  (CHECK-TYPE XD NUMBER)
  (CHECK-TYPE I NUMBER)
  (MULTIPLE-VALUE-BIND (E ED)
      (GET-ERRORS X XD)
    (LET* ((NI (+ I (* E +DT+))) (U (APPLY-CONTROL C E ED NI)))
      (MULTIPLE-VALUE-BIND (NX NXD)
          (INTEGRATE-STATE X XD U)
        (VALUES NX NXD NI (+ (* E E) (* +COST-WEIGHT+ U U)))))))
(DEFUN EXEC-STEP (X XD IE J C)
  "Ejecuta un paso y retorna nuevos valores."
  (MULTIPLE-VALUE-BIND (NX NXD NI CO)
      (STEP-S X XD IE C)
    (VALUES NX NXD NI (+ J (* CO +DT+)))))
(DEFUN SIMULATE (C)
  "Simula oscilador."
  (CHECK-TYPE C FUNCTION)
  (LOOP :WITH X = +X0+
        :AND XD = +XD0+
        :AND IE = +ZERO+
        :AND J = +ZERO+
        :REPEAT +NUM-STEPS+
        :DO (SETF (VALUES X XD IE J) (EXEC-STEP X XD IE J C))
        :FINALLY (RETURN (VALUES J X XD))))
(DEFUN CONTROLLER (E ED I)
  "Controlador PID."
  (+ (* +KP+ E) (* +KD+ ED) (* +KI+ I)))
